### ISSUE TITLE
Software guide is out of date

### ISSUE THREAD

**Issue by prattsj** [LearnersGuild/learning-os-software#170]
The following sections need to be updated:

- (1) Your First Day
  + remove "Slack" section (and renumber following sections)  

- (2) Architecture
  + updated system diagram (https://www.lucidchart.com/publicSegments/view/701b182a-c988-4eea-8231-ecae99571426/image.png)
    - rename `game` to `echo`
    - rename `echo-chat` to `Slack`; remove `LG Customizations`; remove `MongoDB`
    - add `curriculum` (where goal metadata comes from) (linked to echo)
    - add `hubspot` (CRM) (linked to echo and idm)
  + rename "Key Repositories and Services" to "Key Services"
    - Internal Services
      + idm
      + echo
      + curriculum (include "Domains", "Accountabilities", "Endpoint", "Repository")
    - External Services
      + slack
      + hubspot (include "Domains", "Accountabilities", "Endpoint")
  + Add section "Key Libraries"
    - idm-jwt-auth
    - echo-cli  

- (3) Toolkit
  + Shared Tools (folded into main "Toolkit" page)
    - update "Issue Tracking" to refer to refer to github projects instead of ZenHub. developers will need to request an invitation to the organization and a link to the project board.
    - add Slack
      + updated to include only the channel #echo-alerts
      + join learnersguild-dev slack team (request an invitation)
    - add Zoom
    - add Calendar
      + add Phase 4 calendar to your google cal (https://learnersguild.slack.com/archives/C5W5DT35E/p1498498062066374)
        + installing google calendar app (for event alerts)
    - remove sections:
      + "Local Domain..."
      + "Service Generator"
      + "Default Disk Image"
      + "Remote Pairing"
  + (3.1) delete "Shared Tools" page
  + (3.2) delete "Standard Configuration" page  

- (4) Software Development Process
  + replace ZenHub w/ Github Project Board
  + update summary to match simplified workflow (described below)
  + updated workflow diagram:
    - icebox
    - ready for implementation
    - in progress
    - in review
    - closed
  + change "Issue Implementation" header to "GitHub Flow"
  + "Project Board..." updated column names  

- (7) 
  + (7.1) Conventions
    - add top-level `/src` (and indent child dirs)
    - change `/db` to `/data` (with description: "database migrations and source data configuration")  

- (8) Design Guide
  _Remove this entire section_  

- (10) Glossary
  _Best-effort updates_

**Comment by heyheyjp** [comment]
Fixed in https://github.com/LearnersGuild/learning-os-software/pull/172.
